### ISSUE TITLE
how to delete the downloaded things？

### ISSUE THREAD

**Issue by jamninetyfive** [EkoLabs/react-native-background-downloader#1]
em..
how to delete the downloaded things？

**Comment by ptelad** [comment]
Since you are passing the path where you want to save the file
Use a file system library (like react-native-fs) to delete the file at that path.

**Comment by jamninetyfive** [comment]
OK.i will try it. thx

**Comment by jamninetyfive** [comment]
this plugin is a good job.thx ur build.

**Comment by jamninetyfive** [comment]
How to do multitasking download

**Comment by jamninetyfive** [comment]
I want to know how to do multitasking download
If it is react-native-fs, it has an id for each task.
You can use id to pause to resume the download task.
What should I do, thank you
@ptelad

**Comment by ptelad** [comment]
1. Every time you call `RNBackgroundDownloader.download` it creates a new download task.
Call at as many times as you want to download concurrently but please note that iOS manages the downloads, meaning it is up to it how many downloads are actually happening in parallel.

2. Check for existing downloads using `await RNBackgroundDownloader.checkForExistingDownloads()`
it will return all the running download tasks

**Comment by jamninetyfive** [comment]
Thx a lot. I want by coffee for you. Just for thank your help. I slove my problem though your step. @ptelad thank you so much.great job!
