### ISSUE TITLE
checkForExistingDownloads blocking downloads

### ISSUE THREAD

**Issue by PierreBresson** [EkoLabs/react-native-background-downloader#10]
## Expected Behavior
Be able to re-attach downloads.

## Actual Behavior
Re-attaching downloads doesn't work and block new downloads.

## Steps to Reproduce the Problem

  1. Checkout this commit : https://github.com/PierreBresson/Thinkerview/commit/0fd5784f7144d7c71a96ae4219d1d341a53d1c2e

  2. Select an episode and click on "Enregistrer podcast pour une utilisation hors-ligne" : download should work. This triggers savePodcastOffline action.

  3. In `app/screens/offline/index.js` uncomment this.props.resumeDownload(); in componentDidMount. Refresh with command-R, go to the 3rd tab in order to re-attach the download. In the logs, you will see the download to be re-attached but it won’t work since progress isn't logged.

  4. It also affects all RNBackgroundDownloader.download in the app : they no longer work.

(I’ve added the completionHandler in AppDelegate.m)

## Specifications

  - Version: 1.1.0
  - Platform: iOS
  - RN Version: 57.8

**Comment by ptelad** [comment]
What happens if you completely restart the app? Do the downloads work as planned?
Cmd+R can introduce bugs with downloads that users will never experience.

**Comment by PierreBresson** [comment]
Thanks for the answer. Unfortunately, I built the app on device (release) and tried to download a file but the download doesn't start anymore (I've uncomment this.props.resumeDownload();)

**Comment by ptelad** [comment]
This library does not actually download anything, it's just a wrapper for `NSURLSession` on iOS.
If you have problems with downloads, I will check google for issues with `NSURLSession`.

**Comment by pkhodaveissi** [comment]
@ptelad 
can we set timeout for every downloadTask and if it's passed then the download task should change status to DONE or something similar so other downloads can be continuted ?

**Comment by ptelad** [comment]
@pkhodaveissi - The lib doesn't handle the download queue at all, it is all handled natively.

**Comment by omerpucit** [comment]
Currently the version 1.0.1 working fine with checkForExistingDownloads but if i go with latest version then issue come again, even that if i call function pause/resume.
