### ISSUE TITLE
Fetch vs. built-in DownloadManager

### ISSUE THREAD

**Issue by hardcodet** [EkoLabs/react-native-background-downloader#12]
Hi all! I'm (very) new to Android development, and need to build background downloads into my app, and was super happy to have discovered this project. However, I noticed that you are using a (rather outdated) package from Fetch, instead of the built-in DownloadManager, which probably would introduce a more stable feature set (and work similar to its IOS counterpart). In order to make the best decision going forward, I wonder whether there are any reasons we should use a proprietary library like Fetch over the built-in DownloadManager? Thanks for your advice!

**Comment by ptelad** [comment]
Hi!
Thank you for your interest in this library. 
The reasons for not using the built in download manager are:
* Downloads always have a progress notification with the file name
* Downloads are aways shown in the Doan loads app. 

This library is mainly for downloading big files for your app to use. 
Most of the times you don't want the user to have these files in his downloads app and you don't want to disclose the file name in progress notification. 

Overall the built in download manager is less flexible then what most developers want.

**Comment by hardcodet** [comment]
Thanks for the quick reply! That would indeed be a requirement of mine, but that functionality is actually provided by DownloadManager if I didn't misread this:

https://developer.android.com/reference/android/app/DownloadManager.Request#setNotificationVisibility(int)

**Comment by ptelad** [comment]
I saw that you can also choose to make the download not visible in the downloads app.
What I didn't find is a progress callback.
If there is a progress callback, I don't see why we can't use it instead of Fetch (except the dev and QA time ofc)

**Comment by hardcodet** [comment]
From what I can tell (from googling, not expertise ;), there doesn't seem to be a callback of sorts, you'd have to calculate it similar to
https://gist.github.com/tolmachevroman/2c3358faad90aa802dfb

Can't tell whether it would be worth the effort on your end, after all, you already built an integration. OTOH, with a dependency on a system component, you could feel more confident about stability across a wide range of devices, which is such a PITA on Android (and the current Fetch package for example is quite a few bug fixes further than the RC referenced in your package). In any case, thanks a lot for this library! 🚀

**Comment by hardcodet** [comment]
FYI @ptelad 

Attempting to import and run the package on my 0.57 app actually didn't work due to package dependencies, so I guess that would be an example of smth you wouldn't have to worry about using a built-in package:

```
   > Cannot find a version of 'com.android.support:support-core-ui' that satisfies the version constraints:
        Dependency path 'KissMyApp:react-native-background-downloader:unspecified' --> 'com.tonyodev.fetch2:fetch2:2.0.0-RC12' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-fr
agment:27.1.1' --> 'com.android.support:support-core-ui:27.1.1'
        Dependency path 'KissMyApp:react-native-background-downloader:unspecified' --> 'com.tonyodev.fetch2:fetch2:2.0.0-RC12' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:animated-v
ector-drawable:27.1.1' --> 'com.android.support:support-core-ui:27.1.1'
        Constraint path 'KissMyApp:react-native-background-downloader:unspecified' --> 'com.android.support:support-core-ui' strictly '27.1.0' because of the following reason: debugRuntimeClasspath uses versi
on 27.1.0
```

**Comment by ptelad** [comment]
add `implementation 'com.android.support:support-annotations:27.1.1'` to your `build.gradle`

**Comment by ptelad** [comment]
Do you have this line in your app `build.gradle`:
`implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"` ?

**Comment by hardcodet** [comment]
Yes I do. I managed to fix this with the change that is suggested with the pending PR (using `implementation` instead of `provided`).
