### ISSUE TITLE
Undefined is not an object. RNBackgroundDownloader.documents.

### ISSUE THREAD

**Issue by Martlohmus12** [EkoLabs/react-native-background-downloader#13]
Hi,

I installed the package via npm, linked it, and imported it like so.
import RNBackgroundDownloader from 'react-native-background-downloader';
But I am getting error undefined is not an object (evaluating rnbackgrounddownloader.documents)

If I comment it out, another one pops out.

Thank you,

**Comment by ptelad** [comment]
Hi,

Did you rebuild the app?

**Comment by Martlohmus12** [comment]
Hi,

I navigated to android folder and tried to ./gradlew build, which produced the following errors.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-background-downloader'.
      > Could not resolve all dependencies for configuration ':react-native-background-downloader:_debugPublishCopy'.
         > Could not find android.arch.persistence.room:runtime:1.0.0.
           Searched in the following locations:
               file:/usr/local/share/android-sdk/extras/android/m2repository/android/arch/persistence/room/runtime/1.0.0/runtime-1.0.0.pom
               file:/usr/local/share/android-sdk/extras/android/m2repository/android/arch/persistence/room/runtime/1.0.0/runtime-1.0.0.jar
               file:/Users//Documents/isiklik/shoppingListReactNative/android/sdk-manager/android/arch/persistence/room/runtime/1.0.0/runtime-1.0.0.jar
           Required by:
               ShoppingList:react-native-background-downloader:unspecified > com.tonyodev.fetch2:fetch2:2.0.0-RC12
         > Could not find com.android.support:appcompat-v7:27.1.0.
           Searched in the following locations:
               file:/usr/local/share/android-sdk/extras/android/m2repository/com/android/support/appcompat-v7/27.1.0/appcompat-v7-27.1.0.pom
               file:/usr/local/share/android-sdk/extras/android/m2repository/com/android/support/appcompat-v7/27.1.0/appcompat-v7-27.1.0.jar
               file:/Users//Documents/isiklik/shoppingListReactNative/android/sdk-manager/com/android/support/appcompat-v7/27.1.0/appcompat-v7-27.1.0.jar
           Required by:
               ShoppingList:react-native-background-downloader:unspecified > com.tonyodev.fetch2:fetch2:2.0.0-RC12

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by ptelad** [comment]
Do you have this line in your `build.gradle`:
`implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"` or something similar?

**Comment by Martlohmus12** [comment]
I do have following  => .compile "com.android.support:appcompat-v7:23.0.1"
I am using gradle2.2.3

**Comment by ptelad** [comment]
I have no idea what the problem is, did you try rebuilding the project?
Looks like usual Android building issues, if rebuilding doesn't work I would try just googling the error.
This is outside the scope for issues here.
