### ISSUE TITLE
How do I dismiss failed downloads (Android)?

### ISSUE THREAD

**Issue by hardcodet** [EkoLabs/react-native-background-downloader#14]
When I start my app and re-attach to my current downloads, I'm getting two tasks that failed before with error `REQUEST_NOT_SUCCESSFUL`. Which is great (I would want to know that they failed), but now, I'd like to _not_ receive those tasks anymore since I successfully handled them.

I tried `task.stop()`, but that didn't do the trick, so I still get the tasks every time I start my app:

    private onError(task, error) {
        console.warn("Download of task " + task.id + " failed.", error);
        task.stop();
    }

Thanks for your advice!

**Comment by ptelad** [comment]
Hi,
Failed downloads should be removed from the internal maps the module uses.
Can you put a break point in `RNBackgroundDownloaderModule.java:251` and check that is does happen?

Thank you

**Comment by hardcodet** [comment]
The method was definitely invoked and ran through without an exception (I wrapped things in a try/catch block, and the catch was never invoked). I was then happily adding debug code to find out what might be happening, and after the 3rd or 4th restart, the app crashed, and when I restarted again, the downloads were gone (the callback is no longer invoked).

I'll try to repro and repost here if the issue resurfaces.

**Comment by ptelad** [comment]
OK, cool.
I'm closing this issue, if you're able to reproduce it please open a new issue.

**Comment by CodeRabbitYu** [comment]
Have you solved it？ I had this problem

**Comment by CodeRabbitYu** [comment]
[Tell this error message， Id content must be a pure number](https://github.com/EkoLabs/react-native-background-downloader/pull/30)
