### ISSUE TITLE
how  Can i get the task object again when re-launched the app. 

### ISSUE THREAD

**Issue by echokk11** [EkoLabs/react-native-background-downloader#17]
Using the task ID ?
When I start downloading some large file, shutdown the app.
In that time, the job is not completed.
When open the app again.
How can I continue the job(task).

**Comment by echokk11** [comment]
And I found when I used `RNBackgroundDownloader.checkForExistingDownloads()` to continue the task, when the task is finished, the fileSize is not match the original file. It is less than original.

**Comment by ptelad** [comment]
I did not encounter this issue myself.
If this is iOS you're talking about, I would recommend looking up your issue in the context of NSURLSession

**Comment by vlatri** [comment]
@ptelad Hey, it seems `progress` listener doesn't get called if I re-attach to downloads provided by `checkForExistingDownloads`.

**Comment by ptelad** [comment]
@vlatri - these are new task objects and need new listeners, please take a look at the example in the documentation.
