### ISSUE TITLE
Authentication not supported

### ISSUE THREAD

**Issue by hscheckenbacher-ambifi** [EkoLabs/react-native-background-downloader#2]
I really like using this library it certainly helps take care of a lot of headaches. One issue I have and that makes using this library a no-go is the fact that I can't add request headers for downloads. Unless there is a way to do this that's just not documented.

Please advise. Thanks for all the effort!

**Comment by ptelad** [comment]
Thank you for the kind words.
This sound like a great feature to add.

**Comment by ptelad** [comment]
We've added the functionality in v1.1.0.

enjoy!

**Comment by hscheckenbacher-ambifi** [comment]
@ptelad thank you very much!
