### ISSUE TITLE
native module cannot be null

### ISSUE THREAD

**Issue by oakcreations** [EkoLabs/react-native-background-downloader#21]
I did the installation and the link (manual and automatic) and I always have this error when I import the module

react-native-cli: 2.0.1
react-native: 0.57.8
react-native-background-downloader@^2.0.1
iPhone X 12.2
xCode 10.2.1

![Screen Shot 2019-05-15 at 18 53 01](https://user-images.githubusercontent.com/40279711/57812206-bd5c4b00-7742-11e9-9927-799dd44e8fd3.png)

**Comment by divyamakkar26** [comment]
same issue,

**Comment by ptelad** [comment]
Did you rebuild the project in XCODE after the linking?

**Comment by oakcreations** [comment]
@ptelad yes

**Comment by oakcreations** [comment]
any solution ?

**Comment by ptelad** [comment]
@oakcreations - Did you check your xcode build log?
This just sounds like your native code and js code are not in sync.
I would maybe try to unlink and link the lib again, see if that helps.

**Comment by sudipta-pran** [comment]
My React Native version >= 0.60. Do I need to do the manual installation steps for android? I understand I don't need to run link command, but not sure about the other manual steps.
