### ISSUE TITLE
Strive towards backgroundFetch spec

### ISSUE THREAD

**Issue by jimmywarting** [EkoLabs/react-native-background-downloader#23]
I where wondering if you would like to try and follow the [background fetch](https://developers.google.com/web/updates/2018/12/background-fetch) specification. (in some major versoin change/refactor)

After all this seems to be exactly what background fetch is doing. 
Having something that follows a spec and is available in both the web and react native would ease the development and you would not have to duplicate your logic and having to learn how two background download/upload works

**Comment by ptelad** [comment]
Seems reasonable enough but a lot of work.
Are there a lot of developers using react-native on web?

**Comment by jimmywarting** [comment]
> Are there a lot of developers using react-native on web?

My company where I work at tries to reuse same logic/components as much as possible on both mobile and the web.

That was mostly why i wrote this issue.

I don't believe developers are using react-native to build websites but pure react components can work for both web and native as long as it's not too dependent on specific things.
