### ISSUE TITLE
iOS: Downloading from a Share Extension fails

### ISSUE THREAD

**Issue by martinhermida** [EkoLabs/react-native-background-downloader#24]
In iOS, when attempting to perform a download from a Share Extension, it throws the following error: Domain=NSURLErrorDomain Code=-995. NSURLErrorBackgroundSessionRequiresSharedContainer

Taken from [Apple docs](https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html#//apple_ref/doc/uid/TP40014214-CH21-SW2):
> If your app extension initiates a background NSURLSession task, you must also set up a shared container that both the extension and its containing app can access. Use the sharedContainerIdentifier property of the NSURLSessionConfiguration class to specify an identifier for the shared container so that you can access it later.

AFAIK, there is no way of setting up this configuration at the moment, right?

### Specs:
Version: 2.0.1
Platform: iOS 12
RN Version: 0.59.8

**Comment by ptelad** [comment]
A PR with this feature would be appreciated
