### ISSUE TITLE
Application threw exception NSInvalidArgumentException, NSURLSession

### ISSUE THREAD

**Issue by NeliHarbuzava** [EkoLabs/react-native-background-downloader#26]
Hi, I get this error sometimes, when downloading files on real iOS device. And then app crashes.

console output: `Going to download 2097152 bytes!`

`
NSInvalidArgumentException: Application threw exception NSInvalidArgumentException: *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1] Originated at or in a subcall of folly::detail::function::FunctionTraits<bool (folly::dynamic const&, folly::dynamic const&) const>::uninitCall(folly::detail::function::Data&, folly::dynamic const&, folly::dynamic const&)`

```
0x10338ea24
folly::detail::function::FunctionTraits<T>::uninitCall
Called from:
CFNetwork
__113-[NSURLSession delegate_downloadTask:didWriteData:totalBytesWritten:totalBytesExpectedToWrite:completionHandler:]_block_invoke
```

My code:
```
        RNBackgroundDownloader.download({
                id: GeneralService.getRandomId(),
                url: url,
                destination: path + '/' + fileName,
                headers: {
                    'Authorization': ApiService.tokenPrefix + ApiService.token
                }
            })
                .begin((expectedBytes) => {
                    console.log(`Going to download ${expectedBytes} bytes!`);
                })
                .progress((percent) => {
                    console.log(`Downloaded: ${percent * 100}%`);
                })
                .done(() => {
                    resolve();
                    console.log('Download is done!');
                })
                .error((errorMessage) => {
                    Sentry.captureException(new Error(errorMessage));
                    reject(errorMessage);
                    console.log('Download canceled due to error: ', errorMessage);
                });
```

**Comment by NeliHarbuzava** [comment]
Sometimes I get this error at the very begging of the downloading (when only begin() method was called), and sometimes I get this error in the middle of file downloading. I am no familiar with iOS development, so I don't understand what is going wrong with `urlSession`

**Comment by ptelad** [comment]
I'll try to look into it.
Thanks!

**Comment by Dihan101** [comment]
Any update on this guys? I'm still facing this error when I'm trying to download a bulk of 100 images with ranging from 400Kb to 30MB.

**Comment by ptelad** [comment]
Please check if this still happens in 2.1.0

**Comment by FrankGoortani** [comment]
This is happening to me in 2.1.0

**Comment by Dihan101** [comment]
I'm sorry to say this, but I found a solution from another library called "rn-fetch-blob". 
It is very similar to this library and my app did not crash anymore.
Thank me later.

**Comment by vforvasile** [comment]
> I'm sorry to say this, but I found a solution from another library called "rn-fetch-blob".
> It is very similar to this library and my app did not crash anymore.
> Thank me later.

Can you share the link?

**Comment by Dihan101** [comment]
> > I'm sorry to say this, but I found a solution from another library called "rn-fetch-blob".
> > It is very similar to this library and my app did not crash anymore.
> > Thank me later.
> 
> Can you share the link?

Here it is my friend: https://github.com/joltup/rn-fetch-blob
