### ISSUE TITLE
Downloading issues when download documents in bulk on iOS

### ISSUE THREAD

**Issue by divyamakkar26** [EkoLabs/react-native-background-downloader#27]
"react": "16.3.1",
 "react-native": "0.55.4",
 "react-native-background-downloader": "^1.1.0"

Code: 

import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View
} from 'react-native';

import RNBackgroundDownloader from 'react-native-background-downloader';

export default class App extends React.Component {

  startDownload() {
  
    for (let document = 0; document < 500; document++) {
   console.log(`${RNBackgroundDownloader.directories.documents}/${document}/2353_V1_EN.docx`);
      let task = RNBackgroundDownloader.download({
        id: document.toString(),
        url: 'someURL',
        destination: `${RNBackgroundDownloader.directories.documents}/${document}/2353_V1_EN.docx`
      }).begin((expectedBytes) => {
        console.log(`Going to download ${expectedBytes} bytes!`);
      }).progress((percent) => {
        console.log(`Downloaded: ${percent * 100}%`);
      }).done(() => {
        console.log('Download is done!');
      }).error((error) => {
        console.log('Download canceled due to error: ', error);
      });
      console.log(task);
      // Pause the task
      //task.pause();

      // Resume after pause
      //task.resume();

      // Cancel the task
      //task.stop();
    }

  }
  render() {
    return (
      <View style={styles.container}>
        <Text onPress={() => { this.startDownload() }}>Start Download</Text>
      </View>
    );

  }
}

There are multiple issues am facing with iOS downloads. Every time I run this code I see a new error and there is no fix pattern, sometimes it download all the documents.

Errors e.g.
1. Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]'

2. [NSURLSession delegate_downloadTask:didWriteData:totalBytesWritten:totalBytesExpectedToWrite:completionHandler:]

3. Sometimes signal SIGABRT

4. Sometimes downloading doesnt starts

5. Sometime downloading stops in between.

**Comment by ptelad** [comment]
Hi,
I am not sure even regular iOS will handle this properly. 
What's the use case here? 
Background downloads are for downloading a couple large files even after the app has stopped.
Dowabloding 500 small documents in the foreground is a task something else, maybe react-native-fs...

**Comment by ptelad** [comment]
Please check if this still happens in 2.1.0

**Comment by FrankGoortani** [comment]
I'm having the same issue trying to sync a playlist in my audiobook app. When the number is around 20 files, downloads hang and I can only resume them once the app is restarted...
