### ISSUE TITLE
Get downloadId in 'done' callback

### ISSUE THREAD

**Issue by X-Tender** [EkoLabs/react-native-background-downloader#28]
I didn't started working with your lib but how did I get the download id I set at the start in the `done` callback? For example to sync up some data like updating data that file X is available localy now.

**Comment by ptelad** [comment]
`task.id` should work

**Comment by X-Tender** [comment]
Ok, that's what I thought. But that means that I always have to build it up via arrow function to capture the task.id inside it. I think it would be nicer to get the id as a parameter in the callbacks. :)

**Comment by ptelad** [comment]
That a great idea.
I would love to see a PR with this change, it's just a JS file
