### ISSUE TITLE
Exception 'Task created in a session that has been invalidated'

### ISSUE THREAD

**Issue by skantus** [EkoLabs/react-native-background-downloader#31]
I am downloading one file at a time in a queue of scheduled downloads, sometimes the application stops working and later crashing.

# Version:

```
"react-native": "^0.59.9",
"react-native-background-downloader": "^2.0.1",
```

# OS

```
os: iOS 
version: 12.3.1
```

# Code

```javascript

startDownloads = props => {
   this.fetchDownloadRef = RNBackgroundDownloader.download({
        id: props.id,
        url: props.url,
        destination: props.path,
        headers: {
          Authorization: `Bearer ${props.token}`
        }
      });


this.fetchDownloadRef
        .progress((percent) => {
           // progress..
        })
        .done(() => {
           // done
        })
        .error((error: string) => {
          reject(error);
        });
}

startQueue = async () => {
    do {
      await this. startDownloads(this.props);
      this.props.shift();
    } while (this.props);
  };
```

# Tested

```
Simulator
Real device
```

# Attachments

<img width="1404" alt="1" src="https://user-images.githubusercontent.com/4986411/60678697-ab1aa580-9e85-11e9-9d1b-6ed09386bc49.png">

<img width="421" alt="2" src="https://user-images.githubusercontent.com/4986411/60678881-2aa87480-9e86-11e9-8b26-b7ebcd29749c.png">

**Comment by ptelad** [comment]
Is your app in foreground when the download starts?

**Comment by skantus** [comment]
Hi @pieter888, I'm almost sure it happens in the both statuses (background & foreground), I have noticed that it seems to be an authentication problem with the server since it requests a token, the problem is that the response when there is an error is not very explicit at all, but respond well in the request with a `401` if applicable.

**Comment by ptelad** [comment]
Try version 2.1.0, there was a flaw in the way we save references.
Maybe now you'll get clearer errors.

**Comment by skantus** [comment]
@ptelad sure I will try, thank you.

**Comment by FrankGoortani** [comment]
This issue is still happening in 2.1.0

**Comment by behealy** [comment]
I've seen this as well in 2.1.0. @ptelad Out of curiosity, is there a specific reason why `[urlSession invalidateAndCancel];` is being called when there are no longer any tasks in the `taskToConfigMap`?

**Comment by behealy** [comment]
@ptelad To answer my own question.. the docs for NSURLSession states:
>The session object keeps a strong reference to the delegate until your app exits or explicitly invalidates the session. If you do not invalidate the session by calling the invalidateAndCancel or finishTasksAndInvalidate method, your app leaks memory until it exits.

So I can more or less see why `[urlSession invalidateAndCancel];` was added. :)

**Comment by tastyqbit** [comment]
I have just come across this error too. is the [urlSession invalidateAndCancel] definitely the culprit and has anyone found a better fix than allowing memory leaks?

**Comment by sidferreira** [comment]
I'm having this issue on v2.3.4, my test is the following:

starts download `task_1` for file `https://speed.hetzner.de/100MB.bin` and let it finish
starts download `task_2` for file `https://speed.hetzner.de/100MB.bin` and stops it while downloading

try to start `task_1` again

**Comment by sidferreira** [comment]
> @ptelad To answer my own question.. the doc for NSURLSession states:
> 
> > The session object keeps a strong reference to the delegate until your app exits or explicitly invalidates the session. If you do not invalidate the session by calling the invalidateAndCancel or finishTasksAndInvalidate method, your app leaks memory until it exits.
> 
> So I can more or less see why `[urlSession invalidateAndCancel];` was added. :)

The weird part is that the new session is already invalid...

**Comment by leightonkuchel** [comment]
Thanks @sidferreira , that worked a treat! Nice spot 👍
