### ISSUE TITLE
Downloaded file not existing after successfull download

### ISSUE THREAD

**Issue by X-Tender** [EkoLabs/react-native-background-downloader#33]
I've implemented the basic example into my app. After to download is done and output "Download is done!" the FIle doesn't exists. It tries download the FIle to `/data/user/0/com.myapp/files`.

When I test an another Package (rn-fetch-blob) it sucessfully downloadthe file but I can only download it to the Download Folder `/storage/emulated/0/Download`.

I've testing the App on the Emulator.

**Comment by ptelad** [comment]
What is the destination you set when calling `download`?

**Comment by X-Tender** [comment]
I used the `RNBackgroundDownloader.directories.documents` variable

**Comment by ptelad** [comment]
and?
You need to give it a file name at the very least.

**Comment by X-Tender** [comment]
Yes that's what I did :)
I used the same cam from the Example.
https://github.com/EkoLabs/react-native-background-downloader#usage

**Comment by ptelad** [comment]
OK.
Can you please put a breakpoint in 
`- (void)URLSession:(nonnull NSURLSession *)session downloadTask:(nonnull NSURLSessionDownloadTask *)downloadTask didFinishDownloadingToURL:(nonnull NSURL *)location`

Check that the move is successful, maybe something weird is going on.

**Comment by X-Tender** [comment]
Where do I find it? Can I do it also with VSCode or did I have to do it with Android Studio?

**Comment by ptelad** [comment]
Are you using Android?

**Comment by X-Tender** [comment]
Yes

**Comment by ptelad** [comment]
OK, on android things are different.

How are checking if the file is there?

It download to a private folder that belongs to the app.
Try downloading to another path like the Downloads folder you've mentioned just to make sure download works at all on your emulator.

**Comment by X-Tender** [comment]
Yes an another Path works, I've looked into the private folder via a file explorer and its empty.
I could try download it on an native Device, maybe it's really an emulator issue.

**Comment by taibui-rogue** [comment]
I also got this issue. Have you found out why? @X-Tender

**Comment by X-Tender** [comment]
No, I think I have to use an another Path

**Comment by taibui-rogue** [comment]
Oh, in the RNBackgroundDownloaderModule.java file, the document directory is set to "getReactApplicationContext().getFilesDir().getAbsolutePath()".
No wonder why when using RNBackgroundDownloader.directories.documents it always download to /data/user/0/packageId/files.

**Comment by ptelad** [comment]
@taibui-rogue - is that a problem?

**Comment by X-Tender** [comment]
So did you resolved the issue that the correct path gets returned?

**Comment by ptelad** [comment]
I haven't experienced any issues with the path on Android.
I've closed this for lack of activity.

**Comment by X-Tender** [comment]
Would be interesting what kind of path do you get. And on which Android version.

**Comment by paschaldev** [comment]
File does not exist after download... Could this be a permission issue?

**Comment by hariantara** [comment]
@X-Tender I found how to solve for this Directory issue on Android, with help from rn-fetch-blob or using rnfs, in this case I use rn-fetch-blob

example: 

`
import RNFetchBlob from 'rn-fetch-blob';

const startDownload = async () => {
   try {
      const dirs = await RNFetchBlob.fs.dirs; ---> **RNFetchBlob.fs.dirs.DocumentDir**
      console.log('dirs: ', dirs);  -----> look at this directories detail, it base on your storage on android

      /* list of dirs like this (you can choose which one do you want to used)
          DocumentDir: "/data/user/0/sg.com.lovenest.android/files"
          CacheDir: "/data/user/0/sg.com.lovenest.android/cache"
          PictureDir: "/storage/emulated/0/Pictures"
          MusicDir: "/storage/emulated/0/Music"
          MovieDir: "/storage/emulated/0/Movies"
          DownloadDir: "/storage/emulated/0/Download"
          DCIMDir: "/storage/emulated/0/DCIM"
          SDCardDir: "/storage/emulated/0"
          SDCardApplicationDir: "/storage/emulated/0/Android/data/sg.com.lovenest.android"
          MainBundleDir: "/data/user/0/sg.com.lovenest.android"
          LibraryDir: undefined
     */

     // this your **RNBackgroundDownloader** function
   } catch(error) {
     console.log('Error: ', error) 
   }
}
`

**Comment by X-Tender** [comment]
Thank you for the solution @hariantara
