### ISSUE TITLE
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'You must override the `supportedEvents` method of fir_0x6000036d40e0_RNBackgroundDownloader'

### ISSUE THREAD

**Issue by behealy** [EkoLabs/react-native-background-downloader#34]
## Expected Behavior
App will not crash with NSInternalInconsistencyException when running in debug mode.

## Actual Behavior
The following:
```Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'You must override the `supportedEvents` method of fir_0x6000036d40e0_RNBackgroundDownloader'```

First of all, I am by no means an iOS development expert. 

This seems to be happening because of the assertion being performed [here](https://github.com/facebook/react-native/blob/master/React/Modules/RCTEventEmitter.m#L26). 

RNBackgroundDownloader.m definitely has `supportedEvents` implemented (assuming that's all that is needed to "override" the RCTEventEmitter `supportedEvents` method), so I'm not entirely sure why the assertion would be failing. 

## Steps to Reproduce the Problem

1. I downloaded the latest react-native-background-downloader, linked it to iOS project.

2. Then I added the `(void)application:(UIApplication *)application handleEventsForBackgroundURLSession:(NSString *)identifier completionHandler:(void (^)())completionHandler` as mentioned in the installation and setup instructions.

3. Ran the app on a physical device and a simulator in debug mode, using Xcode to run the build.

## Specifications

  - Version: 12.1
  - Platform: iOS
  - RN Version: 0.59.4

## Things I have already tried
- Overriding `+(void)initialize` in RNBackgroundDownloader.m so the assertion isn't even called. This actually solves the issue but later problems come up when trying to call `download` involving other assertions in the RN library code.
- Setting "Debug" to "No" under my project Build Settings > Enable Foundation Assertions.
- Added `NS_BLOCK_ASSERTIONS=1` to Build Settings > Preprocessor Macros > Debug

Release mode is fine, no assertion failures occur. But it would be really really nice to run this in debug mode, so any workarounds or assistance would be appreciated. Thanks for your work on this little library!

**Comment by behealy** [comment]
This feels like it may be more of a bug with React Native, but again.. any suggestions from anyone else would be awesome.

**Comment by ptelad** [comment]
Hi,
Are you using Firebase?
A quick Googling found similar complaints about this error and the culprit seems to be Firebase.

**Comment by FrankGoortani** [comment]
I'm having a similar issue:

> Terminating app due to uncaught exception 'setNativeExceptionHandler', 'You must override the `supportedEvents` method of fir_0x600003377f00_RNBackgroundDownloader

Any help is appreciated!
