### ISSUE TITLE
Background downloading not working

### ISSUE THREAD

**Issue by brave-merida** [EkoLabs/react-native-background-downloader#4]
It's working well when the app is foreground state, but when I press `Home` button and then back to the foreground state, the downloading task was stopped, not progressing.
What's wrong?

iPhone: Both Simulator and Real device
React Native: 0.55.4
XCode: 10.1

```
  componentDidMount() {
    AppState.addEventListener('change', this._handleAppStateChange)
  }
  componentWillUnmount() {
    AppState.removeEventListener('change', this._handleAppStateChange)
  }

  _handleAppStateChange = async nextAppState => {
    if (
      this.state.appState.match(/inactive|background/) &&
      nextAppState === 'active'
    ) {
      // Re-Attaching to background downloads
      let lostTasks = await RNBackgroundDownloader.checkForExistingDownloads()
      for (let i = 0; i < lostTasks.length; i += 1) {
        let task = lostTasks[i]
        if (this.props.episodeId === task.id) {
          console.log(
            'Re-Attaching to background downloads: episodeId=',
            this.props.episodeId,
          )
          this._downloadEpisode(task)
          break
        }
      }
    }
    this.setState({ appState: nextAppState })
  }

  _downloadEpisode = (task = null) => {
    this.setState({ isLoading: true })
    const { episodeId, url, onEpisodeLoaded } = this.props

    if (!task) {
      task = RNBackgroundDownloader.download({
        id: episodeId,
        url,
        destination: this.state.episodePath,
      }).begin(expectedBytes => {
        console.log(`${episodeId}: Going to download ${expectedBytes} bytes!`)
      })
    }

    task
      .progress(percent => {
        console.log(`${episodeId}: Downloaded: ${percent * 100}%`)
        this.setState({ progress: percent })
      })
      .done(() => {
        console.log(`${episodeId}: Download is done!`)
        onEpisodeLoaded({ [episodeId]: this.state.episodePath })
        this.setState({ isLoading: false })
      })
      .error(error => {
        console.warn(`${episodeId} Download canceled due to error: `, error)
        this.setState({ isLoading: false })
      })
    task.resume()
}
```

In AppDelegate.m
```
- (void)application:(UIApplication *)application handleEventsForBackgroundURLSession:(NSString *)identifier completionHandler:(void (^)())completionHandler {
  [RNBackgroundDownloader setCompletionHandlerWithIdentifier:identifier completionHandler:completionHandler];
}
```

**Comment by ptelad** [comment]
Hi there,

You do not need to check for existing download each time you go to background since the JS thread does not die.
You only need to do it when the JS dies and React starts fresh.

Please try to move your re-attachment code to `componentDidMount` and see if this solves your problem.

**Comment by brave-merida** [comment]
Hi @ptelad 
Thanks for your help!
It works well.

**Comment by divyamakkar26** [comment]
@brave-merida you are reattaching the lost task not downloading the task in the background right?

**Comment by brave-merida** [comment]
When I restart an app, if any downloading task is not finished, then I want to reattach the task.

**Comment by divyamakkar26** [comment]
@brave-merida Downloading in the background is not working in iOS (I have enabled background fetch in XCode but it doesn't work for me). Any idea on this?

**Comment by brave-merida** [comment]
@divyamakkar26 , you can use xcode to debug the app.
please share your xcode logs!

**Comment by ptelad** [comment]
@divyamakkar26:
1. You do not have to turn on background fetch for it to work
2. How are testing you background downloads?

**Comment by divyamakkar26** [comment]
@ptelad am putting the app in background and observing my downloading logs

In Android, it is working fine but iOS is not working

**Comment by ptelad** [comment]
@divyamakkar26 did you remember to include [mandatory step](https://github.com/EkoLabs/react-native-background-downloader#ios---extra-mandatory-step)?

**Comment by divyamakkar26** [comment]
@ptelad these are my Xcode logs

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[3]'

**Comment by divyamakkar26** [comment]
@brave-merida 
these are my Xcode logs: 
Thread 27: signal SIGABRT

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[3]'

*** First throw call stack:
(0x1afc5dea4 0x1aee2da50 0x1afbd5384 0x1afb4e404 0x1afb47b68 0x1afb48da0 0x100c4cca0 0x1b03fa08c 0x1b06ed8bc 0x1b05f5ab8 0x1b05f4f8c 0x1b06ef790 0x101893824 0x101894dc8 0x1018981c4 0x101897604 0x1018a61dc 0x1018a6bc8 0x1af87917c 0x1af87bcec)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by ptelad** [comment]
Do the logs tell where the error originates?
It will be really helpful if you could put a breakpoint there and tell us which variable is nil

**Comment by divyamakkar26** [comment]
@ptelad @brave-merida  Please find below the error call stack from Xcode Logs :

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[5]'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010ee501bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010d507735 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010ed9c4ec _CFThrowFormattedException + 194
	3   CoreFoundation                      0x000000010ee2970d -[__NSPlaceholderArray initWithObjects:count:] + 237
	4   CoreFoundation                      0x000000010ee3e2f4 +[NSArray arrayWithObjects:count:] + 52
	5   CoreFoundation                      0x000000010ee48a7b -[NSDictionary allValues] + 251
	6   APP NAME                                0x000000010c1539e5 -[RNBackgroundDownloader URLSession:downloadTask:didWriteData:totalBytesWritten:totalBytesExpectedToWrite:] + 2165
	7   CFNetwork                           0x000000010e76aa22 __113-[NSURLSession delegate_downloadTask:didWriteData:totalBytesWritten:totalBytesExpectedToWrite:completionHandler:]_block_invoke + 50
	8   Foundation                          0x000000010cf74f9e __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	9   Foundation                          0x000000010cf74ea5 -[NSBlockOperation main] + 68
	10  Foundation                          0x000000010cf71c14 -[__NSOperationInternal _start:] + 689
	11  Foundation                          0x000000010cf77c4b __NSOQSchedule_f + 227
	12  libdispatch.dylib                   0x0000000111a1e595 _dispatch_call_block_and_release + 12
	13  libdispatch.dylib                   0x0000000111a1f602 _dispatch_client_callout + 8
	14  libdispatch.dylib                   0x0000000111a2254d _dispatch_continuation_pop + 565
	15  libdispatch.dylib                   0x0000000111a21927 _dispatch_async_redirect_invoke + 859
	16  libdispatch.dylib                   0x0000000111a3000a _dispatch_root_queue_drain + 351
	17  libdispatch.dylib                   0x0000000111a309af _dispatch_worker_thread2 + 130
	18  libsystem_pthread.dylib             0x0000000111ef370e _pthread_wqthread + 619
	19  libsystem_pthread.dylib             0x0000000111ef3435 start_wqthread + 13
)
