### ISSUE TITLE
When download big files after some time got UNKNOWN_IO_ERROR

### ISSUE THREAD

**Issue by MarcosRenato266** [EkoLabs/react-native-background-downloader#40]
### Is this a bug report, a feature request, or a question?

Bug

The questions very simple, when I download big files like videos, after some time of download I got UNKNOWN_IO_ERROR.

**Comment by sayem314** [comment]
Do you have enough free space?

**Comment by sayem314** [comment]
I'm not sure what the exact issue is but I/O error means that something wrong with the disk. Try on other devices and see if it works or not. Also, a sample code would be helpful but hey I'm not the maintainer.

**Comment by MarcosRenato266** [comment]
@sayem314 the problem was tested in other devices, same behavior. But the problem is simulate, just use the start project with this lib and download some movie, the error should happen.

**Comment by sayem314** [comment]
How big is your movie file?

**Comment by MarcosRenato266** [comment]
About to 400mb, but I think that this will be relative to size/Download speed. The solution that I`m using is: when I got some error, I just try to run download again. Looks like when I use Download 2 times with the same path and ID he continue at the point the he stop the last time.

**Comment by sayem314** [comment]
I see. I will download something now that 400MB or bigger and see if any issue on my end. Note that my connection is around 25Mbps.

**Comment by sayem314** [comment]
I was able to download successfully bur there are some issue with this library. Like when I was downloading from google drive it was downloading infinitely (drive don’t provide content-length). And download would start from beginning sometimes (I’m on iOS 13).

**Comment by ptelad** [comment]
Can you try downloading using the test app in this repo?

**Comment by ptelad** [comment]
A month has passed without your reply so I'm closing this.
If you still encounter this issue, please open a new one.

**Comment by smismailalam** [comment]
i am having same issue downloading big file approximate 200mb some time getting time_out error

**Comment by kp72-dev** [comment]
> A month has passed without your reply so I'm closing this.
> If you still encounter this issue, please open a new one.
I am facing that issue right now.
Need Guide and help.

https://github.com/EkoLabs/react-native-background-downloader/issues/91#issue-747230962

**Comment by juninhoall** [comment]
> time_out

Do you solved this problem?
