### ISSUE TITLE
IOS background download

### ISSUE THREAD

**Issue by learnyst** [EkoLabs/react-native-background-downloader#42]
### Is this a bug report, a feature request, or a question?
Question

We are using background downloads in IOS. In our app user can download multiple files at a time. We have implemented multiple downloads as below:

1. User request to download multiple files(Say 30 files)
2. When the user request for download, our app will put all downloads in the queue.
3. After queuing the downloads, our app will give the first download to react-native-background-downloader.
4. Once react-native-background-downloader gives success/failure for the current download, our app will pick next download from queue and give to react-native-background-downloader.

This process is working fine in android. In IOS if the app is in foreground then the process is working. In IOS if the user put app in background after initiating say 30 downloads, then only 1 or 2 downloads are success and after that there is no success/failure response from the react-native-background-downloader.

Questions:
1. I have checked IOS documentation. It says we need to use background-task. Otherwise the system will kill the app after some time 180 sec. Is this the reason for not receiving responses after some time?
2. I have checked  react-native-background-downloader IOS code. I didnot find any background task. Can you please explain how to download multiple files in background if background-task is not created in IOS
3. We are queuing the downloads in our app so that we can show additional status and some app specific stats to user. We are giving one by one download to  react-native-background-downloader. Is this ok or react-native-background-downloader doesnot support this for IOS? in android this is working fine

**Comment by ptelad** [comment]
1. You don't need a background task for downloading in the background, the download itself is a bg task and it is handled by IOS.
2. Again, no need. Setting up you NSURLSession with `[NSURLSessionConfiguration backgroundSessionConfigurationWithIdentifier:sessonIdentifier]` is enough to have downloads in the background.
3. While the download can continue in the background, your app might not, so you need to save your queue in storage (using `AsyncStorage` for example) and load it up at startup and check for existing bg downloading using `checkForExistingDownloads`.

I hope this answers your questions.

**Comment by learnyst** [comment]
Hi,

I my app the logic is like this:
Step-1: Queue all the downloads requested by user
Step-2: Start a download and wait for response
Step-3: When the download finished, we get response from react-native-background-downloader. When the response is received start the next download from queue.

Suppose we start 10 file downloads. And then the app is put to background. I am getting the response for first 2-3 downloads and I am able to start next download also. But after that we are not getting response from react-native-background-downloader. If the app is in foreground then there is no issue. But when the app is in background we are not getting response after 2-3 downloads. This issue is only in IOS

**Comment by learnyst** [comment]
@ptelad any suggestions?

**Comment by ptelad** [comment]
From my experience, giving NSURLSession a lot of downloads and going to the background usually means some of them will fail.
That's just how iOS BG downloads task works, unfortunately.

In your case, I would keep a queue (like you have) and handle all the failures myself when coming from the background.

**Comment by skantus** [comment]
@learnyst you first should to read this:

https://github.com/jamesisaac/react-native-background-task#limitations

The problem is not the library, the problem is run the `queue` logical in your app, there is a way to do it, you could use `rn-fetch-blob` or `react-native-fs` this allow downloads in background too look here:

https://github.com/wkh237/react-native-fetch-blob/wiki/Classes#iosbackgroundtaskboolean
https://github.com/itinance/react-native-fs#background-downloads-tutorial-ios

But I told you this is not the problem, then you have an extra code to do this.
