### ISSUE TITLE
REQUEST_NOT_SUCCESSFUL on Android 4.4 (SDK 19)

### ISSUE THREAD

**Issue by curiousdustin** [EkoLabs/react-native-background-downloader#46]
### Is this a bug report, a feature request, or a question?

Bug / Question

### Have you followed the required steps before opening a bug report?

(Check the step you've followed - put an `x` character between the square brackets (`[]`).)

- [x] I have reviewed [the documentation](https://github.com/EkoLabs/react-native-background-downloader/blob/master/README.md) in its entirety, including the dedicated documentations :books:.
- [x] I have searched for [existing issues](https://github.com/EkoLabs/react-native-background-downloader/issues) and made sure that the problem hasn't already been reported.
- [x] I am using [the latest plugin version](https://github.com/EkoLabs/react-native-background-downloader/releases).

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Android 4.4.

### Is the bug related to the native implementation? (NSURLSession on iOS and Fetch on Android)
Not sure if it is an issue with Fetch. Could not find specific issue in Fetch github.

### Environment

Environment:
    React: 16.8.3
    React native: 0.59.4
    react-native-background-downloader: 2.1.0

  Target Platform:
    Android (4.4)

### Expected Behavior

No errors, in circumstances that work fine on other Android versions.

### Actual Behavior

`REQUEST_NOT_SUCCESSFUL` error for every download attempt on Android 4.4.

### Questions

Is there some additional setup to get this working on Android 4.4?

What is the minimum supported Android version?

**Comment by julitroalves** [comment]
Same issue!
