### ISSUE TITLE
Files aren't created after download done

### ISSUE THREAD

**Issue by franjorub** [EkoLabs/react-native-background-downloader#50]
### Is this a bug report, a feature request, or a question?

bug report

### Have you followed the required steps before opening a bug report?

(Check the step you've followed - put an `x` character between the square brackets (`[]`).)

- [x] I have reviewed [the documentation](https://github.com/EkoLabs/react-native-background-downloader/blob/master/README.md) in its entirety, including the dedicated documentations :books:.
- [x] I have searched for [existing issues](https://github.com/EkoLabs/react-native-background-downloader/issues) and made sure that the problem hasn't already been reported.
- [x] I am using [the latest plugin version](https://github.com/EkoLabs/react-native-background-downloader/releases).

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Android 9

### Environment

  Environment:
    React: 16.8.3
    React native: 0.58.8
    react-native-background-downloader: 2.2.0

  Target Platform:
    Android (9.0)

### Expected Behavior

The download starts and ends as espected 

permission issue ?

### Actual Behavior

![imagen](https://user-images.githubusercontent.com/24401350/66346399-16aa5e00-e920-11e9-9f94-aa7214582b8d.png)
but after complete the file never is created in the files folder or in any side of the app

destination property : 
`       destination: `${RNBackgroundDownloader.directories.documents}/${name}`
`
### Steps to Reproduce
start a new download
display the bytes that it will get
see the progress
see done
file never appears in the storage

**Comment by ptelad** [comment]
Please try version `2.3.0` that was just published, should fix this

**Comment by paschaldev** [comment]
I have this same issue on my Android device... It's never stored in the app's files directory. @franjorub were you able to fix this?
