### ISSUE TITLE
How to get a list of tasks being downloaded

### ISSUE THREAD

**Issue by jamninetyfive** [EkoLabs/react-native-background-downloader#7]
hello.

When I quit downloading routes.
Want to get all download task queue on another routing page.
And how to obtain the situation of each task.

thanks

**Comment by ptelad** [comment]
Hi,

Did you take a look at [Re-attaching to background downloads](https://github.com/EkoLabs/react-native-background-downloader#re-attaching-to-background-downloads)?

**Comment by jamninetyfive** [comment]
yes.i did it.

but when downloading a lot of tasks.about 20+ tasks.

this api will very slow~

**Comment by ptelad** [comment]
This library is meant for downloading large files in the background.
It is not recommended to have more then 4 simultaneously.

Also, the performance is heavily dependent on the phone you use.

**Comment by jamninetyfive** [comment]
First of all, thank you for your reply.
So what should I do, because I can only add all the downloads to the task.
That's why you download four other tasks that will automatically start the list later.
Because I don't know how to do it, two lists, one is downloading and the other is waiting to download.
If there is a task in the download list, the download will be selected from the waiting list.
Because maybe I've left the download routing page.
Is there anything like broadcasting that can be done? I may have any routing with app.

**Comment by jamninetyfive** [comment]
another problem.
IOS when I was downloading
Then kill my application.
Storage space has increased, even if I delete tasks. I will be prompted that I do not have files, but the storage space is consumed.

**Comment by ptelad** [comment]
This might be a problem - could you please provide a code sample that reproduces the issue so we could look into it?
