### ISSUE TITLE
I am trying to download a video but some time the download didn't start like that the download is stuck. another issue is that when after the one download is stuck and if start a new download then the app is crashing. 

### ISSUE THREAD

**Issue by zoobibackups** [EkoLabs/react-native-background-downloader#99]
I have tested this library on iPhone 6 real device and iPhone 11 ios 14.4 there is some issue. sometimes the download is not starting it got stuck. another issue that when one download is stuck and I tried to start a new download then the app is crashing. if ai restart the application and check for the existing downloads then the download begins. how can I solve this issue?

Here is my code. 

`             

               const normaldownload = dispatch => async (url,idsToData1, foldername , name_prefix) => { 
                let idsToData = idsToData1

              try{   
              var date = new Date()
              let filename = `${name_prefix}${Math.floor(date.getTime() + date.getSeconds() / 2)}.mp4`
              const id = `${filename}`;
              const filePath = `${RNBackgroundDownloader.directories.documents}/${id}`;
              idsToData[id]={
                  url,
                  filePath
                }
              AsyncStorage.setItem('idsToData',JSON.stringify(idsToData))
                const task =  RNBackgroundDownloader.download({
                  id: id,
                  url: url,
                  destination: filePath,
                });
                task.pause();
                  task.begin(expectedBytes => {
                    dispatch({type:"DOWNLOAD_SNACKBAR" , payload:{bar:1, path:null}})
                    console.log('Task begin', expectedBytes)
                }).progress(percent => {
                   console.log(percent , 'Progress')
                }).done(() => {
                  delete idsToData[task.id];
                  AsyncStorage.setItem('idsToData', JSON.stringify(idsToData));
                  task.stop();
                      CameraRoll.save(filePath, {'type':'video','album':'VideoDownloader'})
                        .then(() => {
                          dispatch({type:"DOWNLOAD_SNACKBAR" , payload:{bar:2, path:`${foldername}`}})
                          Alert.alert(
                            `Video Saved`,
                            'Video Saved Successfully',
                             [{text: 'OK',}],
                             {cancelable: false},
                          );
                        }).catch(err => {
                            dispatch({type:"DOWNLOAD_SNACKBAR" , payload:{bar:0, path:null}})
                            Alert.alert(
                              'Save Video Failed',
                              'Failed to save video' + err.message,
                              [{text: 'OK', onPress: () => console.log('OK Pressed')}],
                                {cancelable: false},
                              );
                            })
                    }).error((error) =>{
                      dispatch({type:"DOWNLOAD_SNACKBAR" , payload:{bar:0, path:null}})
                      console.log(error, 'Console Log Error')
                    })

                   
          }catch(err){
         
            alert('Some Unknown Error Occured')
          }
        
      }`

**Comment by thesheikhwasim** [comment]
@zoobibackups
Since you have closed this issue without any comments about resolution, can you explain here how you fixed it at your end?
